spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: compose
  data:
    mongodb:
      uri: mongodb://root:password@mongodb:27017/product-service?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8081