spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      uri: "mongodb://root:password@localhost:27017/product-service?authSource=admin"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8081